### ISSUE TITLE
Error sertificate 

### ISSUE THREAD

**Issue by nrmadi02** [theodevoid/wilayah-nusantara#13]
![image](https://github.com/theodevoid/wilayah-nusantara/assets/68098189/a26a256c-d3eb-45c3-b80b-c5a5abe2f232)

**Comment by theodevoid** [comment]
Sorry, ini karena API udah gak di-hosting secara gratis lagi. Saat ini ada sedikit problem finansial pribadi jadi sementara harus cut cost untuk server karena belum ada sponsor. Setelah kondisi finansial mulai recover, free API akan diaktifkan kembali.

**Comment by nrmadi02** [comment]
> Sorry, ini karena API udah gak di-hosting secara gratis lagi. Saat ini ada sedikit problem finansial pribadi jadi sementara harus cut cost untuk server karena belum ada sponsor. Setelah kondisi finansial mulai recover, free API akan diaktifkan kembali.

oke mas.. sorry ya, semoga kedepannya bisa berkembang.
